#Unique Project key (Must be unique in SonarQube)
sonar.projectKey=actions101

#Project name (UI Display)
sonar.projectName=Github Actions101 Project

#Version (Optional but Userful)
sonar.projectVersion=1.0.0

#Sonar Code Location
sonar.sources=src/
#sonar.tests=<test folder location>

# project-root/
# ├── src/
# │   └── your_code.py
# ├── tests/
# │   └── test_code.py
# ├── sonar-project.properties

#Exclusions
sonar.exclusions=**/__pycache__/**,**/pytest_cache/**,**/*.pyc,venv/**,build/**,dist/**

#Test coverage (if using pytest+coverage)
sonar.python.coverage.reportPaths=coverage.xml


#Python Version (Important for correct analysis)
sonar.python.version=3.11

#Encoding 
sonar.sourceEncoding=UTF-8


