name: CI/CD Pipeline - FEATURE
on: 
  push:
    branches: 
       - main
       - feature/*
       - release/*
    tags: 
       - release-*
  workflow_dispatch:

jobs:
  buildJob:
    runs-on: [ self-hosted ]
    environment: Production
    steps: 
        - name: Run command
          run: |
            echo "Hello from the other side"
  devBuildJob:
    runs-on: [ self-hosted ]
    environment: Development
    steps: 
       - name: Run command 
         run: | 
           echo "Hello from dev job"
  