name: CI/CD Pipeline - MAIN
on: 
  push:
    branches: 
       - feature/container-security
    tags: 
  workflow_dispatch:

jobs:
  buildJob:
    # if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: [ ubuntu-latest ]
    steps: 
        - name: Checkout code
          uses: actions/checkout@v3
          with:
             sparse-checkout: 
                app.py
                Dockerfile
                requirements.txt
             sparse-checkout-cone-mode: true
        
        - name: Run trivy scan
          uses: aquasecurity/trivy-action@0.35.0
          with: 
            image-ref: hiireys/actions101:v2
            format: 'sarif'
            output: trivy-results.sarif
            exit-code: 1
            ignore-unfixed: true
            severity: 'CRITICAL,HIGH'
        
        - name: Upload SARIF
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: trivy-results.sarif
          

          # 1. build and push docker image (need a builder, can we try
          # /var/run/docker.sock from the host as we gonna use a wsl runner so 
          # my machine will be the host which has docker desktop

          # 2. setup kustomize and deploy it to kind cluster

          