name: CI/CD Pipeline - MAIN
on: 
  push:
    branches: 
       - feature/container-security
    tags: 
  workflow_dispatch:

jobs:
  buildJob:
    # if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: [ ubuntu-latest ]
    steps: 
        - name: Run command
          run: |
            echo "Hello from the other side"

  