name: Sonar Scan
on: 
  push: 
    branches: 
      - feature/sonar

concurrency:
   group: ci-${{github.head_ref || github.ref_name}}
   cancel-in-progress: true

permissions:
  contents: read #actions/checkout
  security-events: write #to upload sarif file

jobs:
  sonarJob:
    name: job-name-sonar
    runs-on: self-hosted
    environment: Development
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with: 
           sparse-checkout: |
               .snyk
               src/*
               sonar-project.properties
           sparse-checkout-cone-mode: false    
      
      # - name: Sonar On Prem Scan
      #   uses: SonarSource/sonarqube-scan-action@v2  
      #   env:
      #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
      #for sonar on prem and cloud same action
      #use sonarcloud.io for SONAR_HOST_URL for sonarcloud



# Traditional sonar-scanner cli
# Use this to run via new sonar cli, but limited to one file at time https://docs.sonarsource.com/sonarqube-cli/using/commands

      - name: Setup Java for Sonar
        uses: actions/setup-java@v4
        with: 
          distribution: temurin  #Eclipse foundation + Adoptium org merged in (2021) --> new product temurin
          java-version: 17

      - name: Traditional Sonar-scanner cli Setup
        run: |
          
          curl -sSLo scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          # unzip -q scanner.zip #if unzip not avilable use below to unzip

          python3 - << 'EOF'
          import zipfile
          zipfile.ZipFile("scanner.zip").extractall(".")
          EOF

# python3 file.py	  :run file
# python3 -	        :read code from stdin
# << 'EOF' → heredoc (send block as stdin)
# python3 - → read script from stdin
# Together → run inline Python code
# <<- (with dash) → strip leading tabs in heredoc not spaces

      - name: Run traditional sonar-scanner cli scan
        run: |
          export PATH="$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH"
          
          chmod +x sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner
          
          #export PATH="$JAVA_HOME:$PATH" #no need to export as we used setup java action which should set it
          
          java \
          -jar sonar-scanner-5.0.1.3006-linux/lib/sonar-scanner-cli-*.jar \
          -Dsonar.token=${{ secrets.SONAR_CLOUD_TOKEN }} \
          -Dsonar.host.url=${{ vars.SONAR_CLOUD_HOST_URL }} \
          -Dsonar.branch.name=${{ github.ref_name }}


          # sonar-scanner -Dsonar.token=${{ secrets.SONAR_CLOUD_TOKEN }} -Dsonar.host.url=${{ vars.SONAR_CLOUD_HOST_URL }} -Dsonar.branch.name=${{ github.ref_name }}
          #above command didn't work due to java path missing error athough path is correct
